name: bloc_ui_generator
description: "A Dart package for generation of typed BloC widgets like BlocBuilder and BlocListener for concrete implementations"
version: 1.0.10
repository: https://github.com/MaxiSonntag/bloc_ui_generator/tree/main/bloc_ui_generator

environment:
  sdk: ^3.6.0

dependencies:
  analyzer: ^8.0.0
  bloc_ui_annotation: ^1.0.10
  build: ^3.1.0
  source_gen: ^4.0.0

dependency_overrides:
  bloc_ui_annotation:
    path: ../bloc_ui_annotation

dev_dependencies:
  build_runner: ^2.4.7
  test: ^1.25.1
  dart_flutter_team_lints: ^2.1.1
  flutter_lints: ^3.0.2
